### PR TITLE
End of carousel and resize with decimal value for slides to show

### PR DESCRIPTION
**Pull request by earlyster**
when slidesToShow is decimal value ie 3.5 we show 3 and 1/2 of a slide when we are at the end of the carousel and resize we get blank carousel. Also in some cases the order of the slides are not correct.

https://jsfiddle.net/earlyster/q1qznouw/321/

### CODE REVIEW

**Comment by simeydotme** [comment]
@kenwheeler whats the word on floating point `slidesToShow` ? I never even considered this before...

**Comment by kenwheeler** [comment]
I mean, its not officially supported, but even i've used it as a workaround.

**Comment by earlyster** [comment]
Will you accept this pull request?

**Comment by kenwheeler** [comment]
I have to test it thoroughly first

**Comment by earlyster** [comment]
Thanks!

**Pull request merged**
