### PR TITLE
Center even number of horizontal slides when centerMode is true

### PR DESCRIPTION
**Pull request by engelfrost**
Before: http://jsfiddle.net/o7nkhnow/2/ *edit* updated with correct use of `rtl`
After: http://jsfiddle.net/gy1jy44j/2/ *edit* updated with correct fix for `rtl`

This MR centers an even number of slides when `_.slideCount <= _.options.slidesToShow` for horizontal sliders. 

If you want me to test more options please let me know and I'll be happy to do so.

### CODE REVIEW

**Comment by engelfrost** [comment]
I just learned my `rtl` example was wrong. My fix does not work for `rtl` right now, but I'm working on a new commit right now.

**Comment by engelfrost** [comment]
Fixed `rtl`. As noted in the fiddle, there are two issues I have not fixed: 

* Centering only works for horizontal sliders. Vertical sliders are top-aligned. 
* Centering is not fixed for slides with variable width where `_.slideCount <= _.options.slidesToShow`.

**Comment by leggomuhgreggo** [comment]
Nice! I made a [demo](http://codepen.io/leggomuhgreggo/pen/GozOjz?editors=0010) confirming that asNavFor works.

**Comment by simeydotme** [comment]
wow... :clap: ... I've never seen another PR with this amount of tests :)
I'll take a look at them properly, and review the changed code soon :)

Thanks @engelfrost

**Comment by stha** [comment]
Any progress on that? :+1:

**Comment by DJviolin** [comment]
Is it possible somehow to align the screen's left the first slide, when `centerMode` and `infinite` set to `true`? And when you click the next button, it continue from the next slide which needs to be centered (slide 3 for example)?

**Comment by engelfrost** [comment]
@DJviolin If I understand you correctly this PR does not do what you are looking for. There are examples above that demonstrate what this PR does and does not do.

**Comment by mowchan** [comment]
Are there any updates on this or when we may see a release?

**Comment by engelfrost** [comment]
Any progress on getting this merged into master? Is there anything I can help with?

**Comment by leggomuhgreggo** [comment]
Thanks @engelfrost

**Comment by gsm-in** [comment]
Thank you for this wonderful plugin and the update. But it seems that only the slick.js file has been updated and not slick.min.js.

**Pull request merged**
