### PR TITLE
Better handling of lazy loading in webkit-based browsers

### LINKED ISSUE #1032: WebKit not lazy loading cached images on first slide
The opacity of the images remains at 0 because the image.load() is never called. Why is explained here
https://code.google.com/p/chromium/issues/detail?id=7731#c12

This fixes it for me

        function loadImages(imagesScope) {
            $('img[data-lazy]', imagesScope).each(function() {

                var image = $(this),
                    imageSource = image.attr('data-lazy'),
                    imageToLoad = new Image();

                imageToLoad.onload = function() { 
                    image.animate({ opacity: 1 }, 200); 
                }
                imageToLoad.src = imageSource;

                image.css({ opacity: 0 })
                  .attr('src', imageSource)
                  .removeAttr('data-lazy')
                  .removeClass('slick-loading');
            });
        }

### PR DESCRIPTION
**Pull request by thejameskyle**
Fixes #1032 & #1136

### CODE REVIEW

**Comment by kenwheeler** [comment]
Thanks @thejameskyle , I thought I had merged this earlier, just saw it open

**Comment by thejameskyle** [comment]
Would you mind making a quick bug fix release of slick for me? I would like it up on cdnjs

**Comment by kenwheeler** [comment]
1.5.0 is now released. It should hit cdnjs and jsdeliver soon

**Comment by thejameskyle** [comment]
Thanks!

**Pull request merged**
