### PR TITLE
Fix wrong amount of dots in centerMode

### PR DESCRIPTION
**Pull request by danielpuglisi**
Fixes issue #1466

### CODE REVIEW

**Comment by apetrakow** [comment]
does this fix work with `centerMode: false`? 
I have a pretty similar issue here: http://jsfiddle.net/0bnor44n/

**Comment by danielpuglisi** [comment]
No.

You need to set `infinite: false`: http://jsfiddle.net/0bnor44n/1/

If you want it to work with infinite I think you need to change the following lines: https://github.com/danielpuglisi/slick/blob/b7ef77ffb0ef26734d0362df614793bce5ec94e0/slick/slick.js#L981-L985

**Comment by nikitaaswani** [comment]
@danielpuglisi I am also facing the similar issue. I am using centerMode with `infinite: false` and it shows me number of slides + 1 dots. Were you facing the same issue?

**Comment by danielpuglisi** [comment]
@nikitaaswani I don't remember, I don't use slick anymore. It doesn't seem to be maintained anymore anyway.

I'm currently using https://github.com/nolimits4web/swiper in case you need a good alternative slider ;)

**Pull request closed without merging**
