### PR TITLE
Fixes bug in responsive rows

### PR DESCRIPTION
**Pull request by amapparat**
Open since 2015: https://github.com/kenwheeler/slick/issues/1871

### CODE REVIEW

**Comment by leggomuhgreggo** [comment]
Cool, only thing this needs is some test demos. Here's this [codepen template](https://codepen.io/pen?template=ONBMZV) you can use, just replace with your branch

**Comment by danjaywing** [comment]
I'm concerned as myself and two others raised the above 'fix' as breaking for other sliders on the same page. I assume this has been tested in that use case?

**Comment by nyanginator** [comment]
@danjaywing I concur. The fix doesn't really make sense to me. Correct me if I'm wrong, but I believe _.options.rows isn't ever supposed to be <= 0. How else would it distinguish between single-row and multi-row? Should those code blocks really be getting executed in single-row mode?

**Comment by Liroo** [comment]
This PR made slick unusable, going totally in favor of [swiper](https://github.com/nolimits4web/swiper/)...

**Pull request merged**
