### PR TITLE
Add font-display fallback 

### PR DESCRIPTION
**Pull request by mkdgs**
According to lighthouse advice, adding font-display feature
cf. https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=devtools

### CODE REVIEW

**Comment by Vluf** [comment]
It's been over a year, why has this not been merged?

**Comment by mkdgs** [comment]
I forgot that ! It's not a big improvement. I don't know if the project is still alive

**Comment by lukasdoerr** [comment]
Look at the latest changes.. its years ago.

**Review by lukasdoerr — APPROVED** [review]

**Review by ovesh-ampush — APPROVED** [review]
LGTM

**Comment by ovesh-ampush** [comment]
please merge this PR.

**Comment by markvantilburg** [comment]
@ahmadalfy this is solved by using swap such as the pulls: https://github.com/kenwheeler/slick/pull/3899 and https://github.com/kenwheeler/slick/pull/4244

**Comment by ahmadalfy** [comment]
Closed as it is adressed here https://github.com/kenwheeler/slick/pull/3899/

**Pull request closed without merging**
