### PR TITLE
Update slick.scss

### PR DESCRIPTION
**Pull request by markvantilburg**
Fix: #4302 for sass

### CODE REVIEW

**Comment by StephanWagner** [comment]
Please merge, this fixes the deprecated messages in scss

**Comment by IgorNovikov10** [comment]
Please pay attention to this and if possible, merge, this will help us get rid of warnings in development mode

**Comment by markvantilburg** [comment]
@ahmadalfy can you merge this?

**Comment by ahmadalfy** [comment]
Yeah I recently started seeing Sass throwing these warnings because of the addition of nesting to CSS. Let me merge this

**Pull request merged**
