### PR TITLE
Fix a typo and add syntax highlighting language

### PR DESCRIPTION
**Pull request by pra85**
`intialized` → `initialized`
Add syntax highlighting language to HTML, Shell and Javascript code blocks

### CODE REVIEW

**Comment by simeydotme** [comment]
this looks great, @pra85 :D

one quick thing, can you also change
https://github.com/kenwheeler/slick/pull/2144/files#diff-0a369498a5a8db3ac8fa606b544c9810L21
to be a HTML comment? :grin:  -- then I'll merge.

**Comment by pra85** [comment]
@simeydotme Updated the PR with the changes you mentioned :smiley:

**Comment by simeydotme** [comment]
thanks @pra85  :)

**Comment by pra85** [comment]
No problems :+1:

**Pull request merged**
