### PR TITLE
Something wrong with arrows in vertical mode

### PR DESCRIPTION
**Pull request by mazzaker**
Fix for issue #2146 

[Fiddle](https://jsfiddle.net/7zq6m78d/2/)

### CODE REVIEW

**Comment by simeydotme** [comment]
thanks, mazzaker, could you do one more fiddle with a couple of "asNavFor" examples? :) ... the slideHandler method runs TWICE for asNavFor.

**Comment by mazzaker** [comment]
hmm I'll push a new version soon ;)

the nav slider stops if last item is active. Thanks for the hint.

**Comment by mazzaker** [comment]
Hmm there was something wrong with the math of getDotCount. The new version seems to fix the problem but there are so many ways to use slick this is really awesome ;)

This have to be tested with every settings available. Is there a complete test fiddle or something similar?
 
[Fiddle](https://jsfiddle.net/z6njw5z7/2/)

**Comment by leggomuhgreggo** [comment]
@mazzaker here's one from another PR that has a bunch of the settings--just needs to be updated to use this branch: http://jsfiddle.net/gy1jy44j/2/

**Comment by mazzaker** [comment]
[Fiddle with this branch](http://jsfiddle.net/gy1jy44j/4/)

There seems to be a problem with center mode and the number of items <= slidesToShow but this issue is the same on the master.

[Fiddle with master](http://jsfiddle.net/gy1jy44j/5/)

**Comment by mazzaker** [comment]
One more #2035

**Comment by simeydotme** [comment]
## ISOLATED TESTS

@mazzaker -> http://jsfiddle.net/a4ytf12b/
7a79c43f2864ba4087e2961849c2da7bdcfe2de8 **(last commit)** -> http://jsfiddle.net/5y7La0es/

I think it's good to go?

**Comment by ayanapowell** [comment]
Im currently having the same issue. When i set `swipeToSlide: true`, i get too many dots. When set to `swipeToSlide: false`, i get the correct amount of dots...

**Pull request merged**
