### PR TITLE
Fade out previous slide

### PR DESCRIPTION
**Pull request by ethanclevenger91**
Here's the bug in question for #1342 : http://jsfiddle.net/7pvu8gv2/
Fixed: http://jsfiddle.net/m4dL92nq/

Another manifestation: http://codepen.io/ethanclevenger91/pen/PqNxOO
Another fixed: http://codepen.io/ethanclevenger91/pen/jPqQxQ

To say this was rigorously tested might be an overstatement. Let me know if updates should be made.

### CODE REVIEW

**Comment by simeydotme** [comment]
@ethanclevenger91 ... could you take a quick look over: https://github.com/kenwheeler/slick/pull/1344 ( https://github.com/nominalaeon/slick/commit/73c30873295b450f32a417f318b20940bee7da59 ).. does your PR mean that these z-index changes are unecessary, also you can see from @nominalaeon s commits that there's more z-index references than the ones you have erased, could you make sure those other z-index references are not conflicting, or affecting your PR please.
:smile: 

Thanks , Simon.

**Comment by nominalaeon** [comment]
the setFade() function (line 1665) is what makes fade transitions work if you're using the setPosition method to jump between slides. There the z-index ensures that the incoming slide is definitely behind the outgoing no matter what their mark-up order.

It does look like z-index is benign in both setFade() and fadeSlide() but, like I mentioned in #1344, I only noticed the z-index stuff in IE. The z-index declarations are probably just harmless safe-guards for IE compatibility. Chrome and FireFox are deceivingly competent in this department.

But someone's going to have to test in IE8 or 9 to confirm and I'm calling not-it right now.

**Comment by ethanclevenger91** [comment]
My original commit did the trick and surely the z-indexs were there initially for some reason, IE being a likely culprit. No reason I couldn't/shouldn't just revert. Then you guys can continue to address #1344 however you'd planned. Does that make sense?

If we want to be sure, I should have a VM handy for testing IE8.

**Comment by nominalaeon** [comment]
The fix for #1344 is to make zIndex an arg you can pass in. There might be potential use cases for controlling the slide z-index, but that kind of functionality is totally scope creep for a slider.

If the transitions work fine without z-index being set for IE8 (or just IE9? Ken or Simon would have to speak to that), it would be worth dropping them out from both functions.

**Comment by simeydotme** [comment]
Hi @ethanclevenger91 , actually that's not what I was expecting :smile: -- your code addresses a rather prevalent issue which keeps getting raised, so I was hoping to merge it in! :smile: 

But I wanted to make sure we cover those extra few `z-index` assignments:
- https://github.com/ethanclevenger91/slick/blob/629cd590bdd88cbf58589a0da6b24a851e3d9044/slick/slick.js#L1677 
- https://github.com/ethanclevenger91/slick/blob/629cd590bdd88cbf58589a0da6b24a851e3d9044/slick/slick.js#L1685
- https://github.com/ethanclevenger91/slick/blob/629cd590bdd88cbf58589a0da6b24a851e3d9044/slick/slick.js#L1692

If the z-indexes are un-needed now, we can remove them... 
@nominalaeon PR is to allow control of the z-indexes... so if your PR removes the z-indexes, then there's no need for #1344. :) ..... 

__Thus__ my question is: Could you investigate removing those other `zIndex` in your branch? :bow: 

Si.

**Comment by nominalaeon** [comment]
I will, actually I'll just take them out and see if the issue we had on our site is still resolved. brb

**Comment by simeydotme** [comment]
Cool, thanks so much! -- and don't forget to test all the scenarios where `setPosition()` is called :disappointed_relieved:

**Comment by nominalaeon** [comment]
:\ Well without the z-index the slides do not cover my dropdown menu, however, they don't operate at all in IE8. Which is just a terrible thing to say out loud. on the internet. but the client wants compatibility. 

Someone should double-check these results, but what I'm seeing is the last slide on top at full opacity. The dot navigation is blinking between slides, but the last slide is the only one that's ever visible. 

Works fine in IE9 though! I have a slider that runs on a nav-tabs aside that uses setPosition() to jump around and I have the exact same results with it. Borked in IE8, amazing everywhere else.

I have my hack in place in my client's code-base, so that's covered. Ethan's change (when it updates to remove setFade() z-index'ing too) gets my vote. If you want IE8 compatibility, be warned fade-transition is not available. Seems fair to me.

**Comment by ethanclevenger91** [comment]
So sounds like if I clear the rest of the z-index's we...
**Gain:**
Less intrusive on modern browsers
**Lose:**
IE8 compatibility for fade transitions.

I'm fine with that, but want to make sure before I update the commit.

**Comment by nominalaeon** [comment]
ugh, there are a lot of IE8 mentions in the Issues though.

Ethan, does having the z-index property author-able help your situation? We could make a "none" setting too to completely ignore z-index.

**Comment by ethanclevenger91** [comment]
It doesn't affect my _original_ issue at all - like I said, I can revert to the original commit I made that doesn't alter the z-index'ing. If we wanted to add a passable z-index option, I would propose addressing that in another update.

**Comment by simeydotme** [comment]
Alright, no way we can f:cyclone:k up IE8 support, so if you can revert your `zIndex` commit, I'll give this PR a proper testing with a bunch of options and scenarios and hopefully merge it soon... then I'll work with @nominalaeon to rebase and test his branch, too :smiley: 

Thanks for the effort, guys! :bow:
Si.

**Pull request merged**
