### PR TITLE
Fix #1871:  Editing Row amounts for responsive

### LINKED ISSUE #1871: Editing Row amounts for responsive
I have been using slick slider a lot and I love it! I am having an issue with the rows for my responsive settings. I want two rows for desktop which then goes to one row for a smaller screen, the responsive settings recognizes the changes to slide amounts but not rows. The code I have used is below, can you tell me where I am going wrong:

                $('.ptype-slick').slick({
                    infinite: true,
                    arrows: false,
                    rows: 1,
                    slidesToShow: 1,
                    mobileFirst: true,
                    responsive: [
                        {
                            breakpoint: 360,
                            settings: {
                                slidesToShow: 2,
                            }
                        },
                        {
                            breakpoint: 450,
                            settings: {
                                slidesToShow: 3,
                            }
                        },
                        {
                            breakpoint: 600,
                            settings: {
                                slidesToShow: 4,
                            }
                        },
                        {
                            breakpoint: 700,
                            settings: {
                                 rows: 2,
                                slidesPerRow: 5,
                }
            }
                    ]
                });

Many thanks in advcance!
Fiona

### PR DESCRIPTION
**Pull request by babielph**
Hey there,

I fixed following issue: https://github.com/kenwheeler/slick/issues/1871

As you can see I only changed the if condition to also let rows == 1 being affected by buildRows logic and cleanUpRows logic. Since I don't know if that condition had any more sideeffects I hope your testing will figure out if that fix won't break anything!

So long

Charlie

### CODE REVIEW

**Comment by simeydotme** [comment]
@babielph while it's great you're willing to contribute and add value to Slick (and we really appreciate any contributions), it's also up to you to make sure you're not seriously f**king something else up while you do it.

Would you go in to your daily job, throw some JS in to your company's code base and expect someone else to figure out if it was a good fix or a disaster?... not only that; your company also isn't serving millions of companies around the world; each in turn serving their own large customer bases.

Throwing a _"hope your testing figures my shit out, KTHXBYE"_ on your PR has only given me more  incentive to reject and close it. 

However I do note there are a few bugs with Rows. So if you want to test this properly, and provide some evidence, then please by all means do and I'll reopen and reconsider merging. :)

KTHXBYE ;)

**Comment by babielph** [comment]
hey there!

Sorry for my greenhorn behaviour.
Just to point this out - it is my first Pull Request to an open source project - So I need to experience the constraints for doing so ;)

Well I made my own QA while creating a responsive slick slide which finally reacted to a breakpoint row change properly after that fix.

Since I have not that much of an experience (I'm a apprentice developer for half a year now) with CI - I thought that your CI Pipeline which is integrated here would tests the whole.
But it seems that is not the "testing" you would like to see first.

Can you tell me what I can do to make my fix valid in your eyes? What should I test for? Should I create around 50 different kinds of Slides to be sure? Or is there a test suite in this repo which I have not realized?

Please redirect me and teach me how to do it right ;)

Greets Charlie

**Comment by simeydotme** [comment]
No problem, thanks for the understanding and hope it didnt sound too harsh.

I'll do my best to help you out later. Right now it's 6pm on Friday and i'm off for a beer!

**Comment by babielph** [comment]
Go get that beer first !!!!

**Comment by simeydotme** [comment]
Basically @babielph , we'd like to see some before/after JSFiddles... you can find an example in the contribution guidelines. ( http://jsfiddle.net/simeydotme/fmo50w7n/ ) -- change the included slick library to your own one, using rawgit. ( https://rawgit.com/ )

usually for the "fix" we'd like to see a few different option sets, with options that are somewhat related to the change and might cause regression or be affected (you can figure that out by seeing what other methods are called in the method you changed).

without these things, as you pointed out, the burden to verify the fix falls upon us and it can take several weeks/months to get around to doing that.

Best, Simon.

**Pull request closed without merging**
