### PR TITLE
Center active slide in infinite vertical center mode

### PR DESCRIPTION
**Pull request by illarionvk**
Fixes issue #2214 

Before: [http://jsfiddle.net/7Lyr8o2q/](http://jsfiddle.net/7Lyr8o2q/)
After: [http://jsfiddle.net/illarionvk/w07tuo44/](http://jsfiddle.net/illarionvk/w07tuo44/)

### CODE REVIEW

**Comment by aleemb** [comment]
@kenwheeler any chance of merging this?

**Comment by leggomuhgreggo** [comment]
Dope. Thanks @illarionvk

**Comment by naumanjkhan** [comment]
@leggomuhgreggo Requested PR has a bug, it will break if `centerMode: false` or `missing`

[Center mode missing](http://jsfiddle.net/w07tuo44/16/)
[Center mode false](http://jsfiddle.net/w07tuo44/17/)

**Comment by leggomuhgreggo** [comment]
Reverted. Thanks for chiming in. Not sure how I missed that in my testing. Much appreciated @naumanjkhan

**Pull request merged**
