### PR TITLE
No need to do this

### PR DESCRIPTION
**Pull request by psquickitjayant**
Causing delay in the index change when slides are changed frequently using external control.

### CODE REVIEW

**Comment by kenwheeler** [comment]
This removes the callback wait when things are CSS animated. If you are using slickGoTo, use the dontAnimate argument

**Comment by psquickitjayant** [comment]
I need to animate slides when using slickGoTo. Here it is my sample code. 
Using frequent switches from one slide to another by slickGoTo function is giving wrong index. 

```
$('.cn1inner-slider').slickGoTo(index, false);
```

**Comment by kenwheeler** [comment]
If that works for your use case, that's cool, but it's not grounds to neuter the core library.

**Comment by psquickitjayant** [comment]
Cool! Thanks!

**Pull request closed without merging**
