### PR TITLE
Typo on README

### PR DESCRIPTION
**Pull request by sonyarianto**

### CODE REVIEW

**Comment by Daniel217D** [comment]
The most important pull request!

**Comment by sonyarianto** [comment]
@Daniel217D yes obviously, this is super important for Slick JS future development hahahah

**Comment by markvantilburg** [comment]
same as https://github.com/kenwheeler/slick/pull/3647

**Comment by markvantilburg** [comment]
@ahmadalfy can you close this one

**Comment by ahmadalfy** [comment]
Closing as this was fixed in a different PR

**Comment by sonyarianto** [comment]
OK OK, I lost :)

**Pull request closed without merging**
