### PR TITLE
Update: Fix Issue #2035 - Extra dot when slide count was not divisibl…

### PR DESCRIPTION
**Pull request by taylorKonigsmark**
I believe the problem with issue #2035 was that the slide count was not divisible by the slides being shown.

jsfiddle of bug fix and various features that have to do with slideToShow/slideToScroll:

https://jsfiddle.net/parcotk/73qpkva2/5/

Please let me know if there is anything i can do to better this. I want my first PR to be for this great project!

### CODE REVIEW

**Comment by kenwheeler** [comment]
Now thats a pull request!

**Comment by ahmadalfy** [comment]
Interesting ... I never noticed that bug before

**Comment by kaptenw** [comment]
@taylorKonigsmark, the issue still exists when having `16` slides with `slidesToShow: 4, slidesToScroll: 3`:
https://jsfiddle.net/mqgq5rg7/1/ (the next to last slider)
As I said, don't ask about that setup...

**Comment by taylorKonigsmark** [comment]
Yea, I see the issue :(

I spent a couple of hours the last couple of days trying to figure it out, and haven't been successful. Could really use some help from someone to familiarize my with this project.

**Comment by kenwheeler** [comment]
So this 4,3 error, this occurs both before and after?

**Comment by taylorKonigsmark** [comment]
before and after the merge? correct

**Comment by simeydotme** [comment]
I think I've just found a breaking change with this PR.
Gonna do a little more testing, and might have to revert the merge ... hold on to your butts...

**Comment by ahmadalfy** [comment]
@simeydotme crossing fingers

**Comment by mazzaker** [comment]
It seems that #2152 solve this problem

[Fiddle with 2152](https://jsfiddle.net/mqgq5rg7/3/)

**Comment by truefalse10** [comment]
@simeydotme I still get the bug of the additional dot here:

[Fiddle with additional dot](http://jsfiddle.net/H66vv/28/)

**Comment by mazzaker** [comment]
Change the slick.js to the current master:
[Fiddle](http://jsfiddle.net/H66vv/29/)
[slick.js](https://rawgit.com/kenwheeler/slick/master/slick/slick.js)

**Comment by truefalse10** [comment]
Thank you. The latest update solves this problem

**Pull request merged**
