### PR TITLE
Add a Gitter chat badge to README.markdown

### PR DESCRIPTION
**Pull request by gitter-badger**
### kenwheeler/slick now has a Chat Room on Gitter

@kenwheeler has just created a chat room. You can visit it here: [https://gitter.im/kenwheeler/slick](https://gitter.im/kenwheeler/slick?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.markdown:

[Gitter](https://gitter.im/kenwheeler/slick?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by simeydotme** [comment]
hahah, is that a PR from a robot??

**Comment by kenwheeler** [comment]
@simeydotme yup, did it when I signed up. Have you seen it?

**Comment by simeydotme** [comment]
Nope, any good?

**Comment by kenwheeler** [comment]
Closing as a dupe, because you add it in the other one

**Pull request closed without merging**
