### PR TITLE
Rebuild rows after breakpoint

### PR DESCRIPTION
**Pull request by sebastiancichos**
Add breakpoint rebuild row when number of rows is one or more

### CODE REVIEW

**Comment by sebastiancichos** [comment]
@kenwheeler lookup this

**Comment by emgiezet** [comment]
+1

**Comment by kamdz** [comment]
+1

**Comment by oparkadiusz** [comment]
+1

**Comment by kamillo1888** [comment]
+11 ! oneoneone! eleveneleven!

**Comment by kwojc** [comment]
+1!one!sin(90)

**Comment by pawelkolanowski** [comment]
+111

**Comment by kenwheeler** [comment]
:fireworks:

**Comment by emgiezet** [comment]
can you add tag? plz

**Comment by sebastiancichos** [comment]
@emgiezet +1

**Comment by kenwheeler** [comment]
Tag?

**Comment by sebastiancichos** [comment]
up version to bower repo

**Comment by kenwheeler** [comment]
Reverted, this broke master

**Comment by kenwheeler** [comment]
If rows === 1, why do you need to rebuild them. they shouldn't be there at all?

**Comment by kenwheeler** [comment]
Can you show me an example in a jsfiddle of what this is supposed to fix?

**Pull request merged**
