### PR TITLE
#1207 White spaces when using variableWidth and infinite to true

### PR DESCRIPTION
**Pull request by nicolaspernot**
Solve the #1207 issues about white spaces when using variableWidth and infinite to true, solution gave by xXanth0s (https://github.com/kenwheeler/slick/issues/1207#issuecomment-263908723)

### CODE REVIEW

**Comment by leggomuhgreggo** [comment]
Hey can you demo your changes in a pen, and then maybe test it against some of the existing functionality in [this test template](https://codepen.io/pen?template=ONBMZV)

Thanks!

**Comment by nicolaspernot** [comment]
Here is it : https://codepen.io/nicolaspernot/pen/WOZwzQ

I added an example of a slider with variableWidth: true and  infinite: true.
Solution is clearly better but seems not perfect when slides width are not exactly the same as the sliders width. But better. I'll try to fix this last bug in a near future.

For the other sliders demos, I noticed no problem, except maybe some changing in green and pinky colors. But I think it's nothing else than CSS improvement.

**Comment by leggomuhgreggo** [comment]
@nicolaspernot cool flashing is from the clone swap, and is known issue.

Did you want to go another round on this or you feelin a "perfect is the enemy of good" merge?

**Comment by nicolaspernot** [comment]
@leggomuhgreggo I know I will correct the last issue because I work for someone who want it solved. He wants it solved, but it is not his priority. A day I will, for sure :)
So, I think it's for the better to merge now and let's create an issue for the remaining issue.

By the way, yes, i'm a perfect-is-the-enemy-of-good guy :)

**Comment by leggomuhgreggo** [comment]
Thanks! Merged

**Pull request merged**
