### PR TITLE
Add support for Composer

### PR DESCRIPTION
**Pull request by derhasi**
For future releases it was great you could add this composer.json and add the package to packagist.org :)

### CODE REVIEW

**Comment by deefour** [comment]
I'm genuinely curious why this would be desirable. [Composer](https://getcomposer.org/) is the **"Dependency Manager for PHP"**, not Javascript. That's what [NPM](https://www.npmjs.com/), [Jam](http://jamjs.org/), [Bower](http://bower.io/), and others are for.

Would you suggest adding a `slick.gemspec` file too, so it can be added to RubyGems to be installable via [Bundler](http://bundler.io/)?

**Comment by derhasi** [comment]
Composer is a dependency manager for PHP projects. That does not mean that the package have to be php, as you will use non-php packages in php projects too.

Besides that, npm, jam and bower are package managers that run on node. Why shouldn't a PHP based package manager not be allowed to handle Javascript-Packages?

I personally do not use Ruby for webdevelopment, but I do not see a reason, why that should not be a valid request.

If the maintainer of this project does not want that, that's fine. But then we would need to maintain a fork to do it anyways.

**Comment by MariusRumpf** [comment]
Why not use the [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin) for this. This has the possibility to add sources from npm/bower in your `composer.json`.

**Comment by derhasi** [comment]
Because it Is slow and it does only work when the plugin is installed globally. These are two crucial problems.

**Comment by simeydotme** [comment]
I'm kind of on @deefour 's level here...
I've not seen a composer.json file in pretty much any frontend libraries before... https://github.com/jquery/jquery jQuery doesn't have it, so dependencies wouldn't be met, anyway?

I'll close this, but I'm pinging @kenwheeler so he can have one final [goosey](http://www.urbandictionary.com/define.php?term=goosey) and bring it back from the grave if he wants *composer.json* support :smile: 

Thanks for your effort, @derhasi . :)

**Pull request closed without merging**
