### PR TITLE
Feature #2054 - Add event 'lazyLoaded' so user can listen for when image loads successfully

### PR DESCRIPTION
**Pull request by taylorKonigsmark**
https://jsfiddle.net/parcotk/txm44hsw/3/

i added an event that should help resolve feature #2054 

Let me know if there is anything that I should change.

### CODE REVIEW

**Comment by simeydotme** [comment]
Thanks, @taylorKonigsmark ...
Could you do me a favour and run: 
```shell
$ git rebase -i HEAD^5
```
on your fork and squash all your commits in to one? :) -- it's a bit messy having those `revert` commits :+1:

**Comment by taylorKonigsmark** [comment]
@simeydotme Sorry, still getting used to git :)

For my knowledge, we're moving the event trigger inside the animate function because that is the final step when it is loaded correctly?

**Comment by simeydotme** [comment]
correct, @taylorKonigsmark  :) -- better not fire the event before the image is visible, I think :)
don't worry about git, after a couple of times rebasing, you'll be a pro ;) -- hop in to slick on Gitter if u need help.

**Comment by taylorKonigsmark** [comment]
I think everything is set @simeydotme, does @kenwheeler need to approve?

**Comment by simeydotme** [comment]
Thanks @taylorKonigsmark ... http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html , sorry to hound you for a rebase, but it's 2 lines of code currently spread across 6 commits :cold_sweat:

**Comment by taylorKonigsmark** [comment]
holy moly what a learning curve this is! did that work? haha. Otherwise... I need to buy a book for git

**Comment by simeydotme** [comment]
🙈 Haha, so sorry @taylorKonigsmark ... I have no idea what happened, but that's definitely not what I was expecting to see 😛😘 ... I'll try to sort this out tonight, please sit tight 🙇

Thanks so much for your effort!

**Comment by taylorKonigsmark** [comment]
Thanks @simeydotme. Honestly you can scrap the PR and put it in yourself if that is easier. I'm just trying to help out where I can. I think that my problem was that I renamed a branch for this new feature. Now I learned that was a bad move ha-ha.

**Comment by simeydotme** [comment]
closed by #7abc8d9

**Pull request closed without merging**
