### PR TITLE
Make sass file more configurable

### PR DESCRIPTION
**Pull request by Jako**
It would be nice to be able to change the arrow font-size and arrow font-weight by variables.

### CODE REVIEW

**Comment by simeydotme** [comment]
not really essential, sorry

**Comment by simeydotme** [comment]
adding "more configuration" as a consideration

**Comment by Jako** [comment]
That way the default SCSS file is not usable and has to be duplicated, when a different font than slick is used. A lot of things in the theme file are configurable. Why not the font size and the font weight.

**Comment by rudzboy** [comment]
+1

**Pull request closed without merging**
