### PR TITLE
Wrong less syntax

### PR DESCRIPTION
**Pull request by laurent-bettin**
Hi,

In think there are some error in less file. The way you use ampersand generate the wrong rules eg :
.slick-slide.slick-initialized instead of .slick-initialized .slick-slide.

### CODE REVIEW

**Comment by kenwheeler** [comment]
@leggomuhgreggo is this right? I don't work with less like that

**Comment by leggomuhgreggo** [comment]
Oooo, might be. I'm on it.

**Comment by leggomuhgreggo** [comment]
Thanks for catching that @laurent-bettin 

Fixed in #1747

**Comment by laurent-bettin** [comment]
:+1:

**Pull request merged**
