### PR TITLE
Aligns slides in the center

### PR DESCRIPTION
**Pull request by corvus-007**
Aligns slides in the center if the number of slides is less than slidesToShow.
https://codepen.io/corvus-007/pen/LLdPqx?editors=1100

### CODE REVIEW

**Comment by tkuther** [comment]
Looks related to #1901

**Comment by leggomuhgreggo** [comment]
Couldn't think of any instance where this'd mess things up. Looked good in my testing. My only hesitancy is adding styles that might (in some unknown case) conflict, entropy yada yada, but it's the theme file which is optional, so I'm going to green light it. 

Thanks for the PR

**Comment by mfeltscher** [comment]
This breaks existing setups with `centerMode: false` and a small number of slides which should be left aligned.

**Comment by DanielRuf** [comment]
> This breaks existing setups with centerMode: false and a small number of slides which should be left aligned.

Exactly. Also by default this was not centered before so this is a breaking change.

**Comment by warudin** [comment]
Since 1.7 sliders with a small number of slides are lined out in the center, but in various cases this isn't the desired effect. What setting do I use to prevent this?

**Comment by DanielRuf** [comment]
> Since 1.7 sliders with a small number of slides are lined out in the center, but in various cases this isn't the desired effect. What setting do I use to prevent this?

You have to reset the margins.

**Pull request merged**
