### PR TITLE
Pauses autoplay with onTouch event

### PR DESCRIPTION
**Pull request by MikeMcNuke**
Hi, here's the pull request for the touchEvent and autoplay function.

### CODE REVIEW

**Comment by simeydotme** [comment]
Could you please explain what this is for, why it is needed and provide a demo ([jsfiddle boilerplate](http://jsfiddle.net/simeydotme/fmo50w7n/)) of behaviour before and after?

**Comment by MikeMcNuke** [comment]
Will add a boilerplate this week, problem is that if you touch the slide on tablet/phone it doesn't stop sliding. Similar to pauseOnHover it is just a pauseOnTouch.

**Comment by simeydotme** [comment]
can you test if the master branch is behaving how you expect? 
http://jsfiddle.net/ereLupxh/1/embed/result/

**Comment by simeydotme** [comment]
just tested on my Android.
this issue is fixed/closed with an "autoplay-rewrite" from #2060 :)

**Pull request closed without merging**
