### PR TITLE
Dots fix on slidesToShow

### PR DESCRIPTION
**Pull request by ethanclevenger91**
Here's broken again: http://codepen.io/ethanclevenger91/pen/xwYERX/

Here's fixed: http://codepen.io/ethanclevenger91/pen/WQMGaw

In `getDotCount()` I swapped the breakpoint increment to `slidesToScroll` rather than `slidesToShow`.

Unrelated: I noticed in the master branch, `slick.js` (updated < 1 month ago) causes the slide animation to look strange. Draggy? Gross? Either way, not as clean as the `slick.min.js` being served up by CDNjs, v1.5.8. I think a change may have been made that affected this. I edited and fixed both in my branch, so if you look at the fixed pen, it's currently set to load my new `slick.min.js` based on the CDNjs v1.5.8 (which is probably the same as master). If you go into the JS resources and swap `dots-fix/slick/slick.min.js` for `dots-fix/slick/slick.js`, you'll see the draggy animation I'm talking about. I can roll back my changes to `slick.min.js` before merging if you want.

### CODE REVIEW

**Comment by ethanclevenger91** [comment]
Oh, fixed #1838

**Comment by ethanclevenger91** [comment]
Figured out the funny animation, related to https://github.com/kenwheeler/slick/pull/1632 - needed to set `useTransform:true`. Rolling back changes to min.

**Comment by ahmadalfy** [comment]
Looks good to me! Let's wait for @kenwheeler

**Comment by miscbits** [comment]
http://codepen.io/anon/pen/yYrOGP

Haven't checked if this is related to the fix or if this is already an issue in slick, but when slides to scroll is less than slides to show (here its 2) then there is one too many dots.

**Comment by ethanclevenger91** [comment]
Hm, it's not even necessarily that there are too many dots - for the third dot, the slides don't respond, but the last dot scrolls _3_ slides instead of 2.

**Pull request merged**
