### PR TITLE
switch keyHandler position in rtl

### PR DESCRIPTION
**Pull request by boynet**
In rtl the 'left' arrow should swipe next and right arrow should swipe prev

### CODE REVIEW

**Comment by simeydotme** [comment]
@boynet ... are you a native "rtl" user ? 
Have you got some documentation on hand that specifies a computer with `rtl` support means the `left` arrow goes `right` ? -- this seems crazy :stuck_out_tongue_closed_eyes: 

Please rebase and reopen with requested documentation, then I'll see about merging.

Best, Si.

**Comment by boynet** [comment]
1 year for this simple pr :)
I don't have any official document but i am native rtl user and yes, just like you read from right to left, the books are open from right to left.
anyway we can make it as option parameter

you can see in this video how she read the book:
https://youtu.be/dI9baxD6kmA?t=51s

**Comment by boynet** [comment]
I think you didn't understand this pr I will explain:
take a look at the ````Slick.prototype.keyHandler```` function
now open the rtl demo http://kenwheeler.github.io/slick/

you see in the demo than the arrow on the left side is the one who is scrolling next and the arrow at the right is the one who is previous?.

now in the rtl demo press the left arrow in your keyboard you see how the left arrow is taking you previous instead of next? this what I tried to fix in this pr

**Comment by simeydotme** [comment]
> 1 year for this simple pr :)  

  We;ve been busy :disappointed:   

---

After seeing the demo it makes more sense :smile: -- apologies.
I'd be happy to merge if you can rebase and push again. :)

**Comment by boynet** [comment]
sorry I cant :( can only delete my fork and create a new pr, is it ok?

**Comment by simeydotme** [comment]
_and it's not about the complexity of the pr that made it take so long, it's due to the other 100 "simple" prs for "simple" things with no jsfiddle demonstrating the before/after effects, and no proper explanation meaning we have to sit there and figure out every one of them... also the 100 other prs for not simple things... also trying to sort through 400+ issues and having a life and doing a full time job and trying to maintain other projects for our lovely users..._

sorry for that rant, and I think your comment was not meant to harm... especially since you removed it quickly :smile:  but for something simple to you, it's not always the same for the other side :disappointed:

**Comment by simeydotme** [comment]
@boynet yes you can create new PR, hope it's not too much effort :)

**Comment by simeydotme** [comment]
closing for #2069

**Pull request closed without merging**
