### PR TITLE
Optional use of transform

### LINKED ISSUE #1631: Embedded iframe w/video on Firefox (Windows.8.1)
Hi,

I'm having a very specific issue with Firefox v. 40.0 on Windows 8.1.
 I'm embedding a video via iframe and using it as an item in slick. The use of css transforms `transform:translate(640px,0px);` causes the video controls to behave weirdly. 

I'm pretty sure that this is a bug with the way Firefox is dealing with transforms/flash, however, I think that the use of transforms should be able to be overridden anyway. 

#1143 
Without the change:
http://plnkr.co/edit/5EX3XWRQTgnBYzwqUrot?p=preview

With the option disabled:
http://plnkr.co/edit/a4ZB7rni7f4QDrDKB83b?p=preview

ref - #1143

### PR DESCRIPTION
**Pull request by marcellscarlett**
Fixes #1631, #1143

### CODE REVIEW

**Comment by kenwheeler** [comment]
Thanks dude

**Comment by electerious** [comment]
The default of `useTransform` should be `true`. Performance is so much better when using `transform`. Disabling it will lead to a lot of user never knowing that you can turn it on. Looks like there're only a few edge-cases where you really need to turn it off.

**Comment by SaraSoueidan** [comment]
Hey! I'm currently using the Slider in a project and wanted to point out the importance of having `useTransform` enabled by default. As @electerious mentioned, the performance difference is very big and all performance experts recommend using transforms and not position properties to animate elements.

It would also be nice to add the `useTransform` option to the list available on the plugin homepage, because I couldn't find it without Googling which got me to this thread here.

Cheers!

**Comment by leggomuhgreggo** [comment]
Hey @SaraSoueidan `useTransform` is set to `true` by default in the master. New release is coming soon. Thanks!

**Comment by SaraSoueidan** [comment]
Awesome. Cheers!

**Pull request merged**
