### PR TITLE
beforeChange event; event.preventDefault() to block slide change

### PR DESCRIPTION
**Pull request by adam-lynch**
Related to #1138

### CODE REVIEW

**Comment by nfour** [comment]
+1

**Comment by nfour** [comment]
Unfortunately this breaks #1179 as it seems to prevent events from propagating down into children slick sliders.

**Comment by adam-lynch** [comment]
But events don't propagate down. I'll reply on #1179.

**Comment by c0necto** [comment]
+1

**Comment by simeydotme** [comment]
Oh, this looks like a good addition... 
@adam-lynch are you still intertested in having it merged? -- I can review it if you could rebase, and also create a quick JSFiddle demonstrating the functionality with a few  options / breakpoints? :) (use contributing.md one as base)

**Comment by simeydotme** [comment]
@adam-lynch I'll give you one last nudge, because this is highly requested.
If you can't do a rebase and add a JSFiddle, I'll have to close the PR :smile:

**Comment by adam-lynch** [comment]
It's not that I can't, I don't want to. Will be moving away from slick.
Feel free to close :)

**Comment by simeydotme** [comment]
Sure, that's a shame :disappointed:

**Comment by alizbazar** [comment]
:(

**Comment by cfoehrdes** [comment]
The missing jsfiddle and documentation was the only problem with this PR? We also need this feature and I am willing to reopen one in a proper way including the missing stuff.

@simeydotme If you have any other suggestions please let me know and I add them.

**Comment by simeydotme** [comment]
yes @cfoehrdes .. but I pulled @adam-lynch 's fork in to my own branch, and began testing and found many bugs regarding other options such as "asNavFor" ... I gave up with it because it was too buggy :(

**Comment by cfoehrdes** [comment]
Ok, I will give it a try. I will let you know if I was successful

**Pull request closed without merging**
